/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_enature_AnSurfaceView */

#ifndef _Included_com_enature_AnSurfaceView
#define _Included_com_enature_AnSurfaceView
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_enature_AnSurfaceView
 * Method:    OnSurfaceCreated
 * Signature: (Landroid/view/Surface;)V
 */
JNIEXPORT void JNICALL Java_com_enature_AnSurfaceView_OnSurfaceCreated
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_enature_AnSurfaceView
 * Method:    OnSurfaceDestroyed
 * Signature: (Landroid/view/Surface;)V
 */
JNIEXPORT void JNICALL Java_com_enature_AnSurfaceView_OnSurfaceDestroyed
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_enature_AnSurfaceView
 * Method:    OnSurfaceChanged
 * Signature: (Landroid/view/Surface;)V
 */
JNIEXPORT void JNICALL Java_com_enature_AnSurfaceView_OnSurfaceChanged
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
