/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_bigital_shaderdemo_MainActivity */

#ifndef _Included_com_bigital_shaderdemo_MainActivity
#define _Included_com_bigital_shaderdemo_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_bigital_shaderdemo_MainActivity
 * Method:    onSurfaceCreated
 * Signature: (Landroid/view/Surface;)V
 */
JNIEXPORT void JNICALL Java_com_bigital_shaderdemo_MainActivity_onSurfaceCreated
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_bigital_shaderdemo_MainActivity
 * Method:    onSurfaceChanged
 * Signature: (Landroid/view/Surface;)V
 */
JNIEXPORT void JNICALL Java_com_bigital_shaderdemo_MainActivity_onSurfaceChanged
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_bigital_shaderdemo_MainActivity
 * Method:    onSurfaceDestroy
 * Signature: (Landroid/view/Surface;)V
 */
JNIEXPORT void JNICALL Java_com_bigital_shaderdemo_MainActivity_onSurfaceDestroy
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
