/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_bigital_shaderdemo_MainActivity */

#ifndef _Included_com_bigital_shaderdemo_MainActivity
#define _Included_com_bigital_shaderdemo_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_bigital_shaderdemo_MainActivity
 * Method:    OnSurfaceCreated
 * Signature: (Landroid/view/Surface;)V
 */
JNIEXPORT void JNICALL Java_com_bigital_shaderdemo_MainActivity_OnSurfaceCreated
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_bigital_shaderdemo_MainActivity
 * Method:    OnSurfaceChanged
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_bigital_shaderdemo_MainActivity_OnSurfaceChanged
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_bigital_shaderdemo_MainActivity
 * Method:    OnDrawFrame
 * Signature: (Landroid/graphics/Bitmap;)V
 */
JNIEXPORT void JNICALL Java_com_bigital_shaderdemo_MainActivity_OnDrawFrame
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
